repos:
- repo: local
  hooks:
  - id: markdownlint_docker
    name: Markdownlint Docker
    description: Run markdown lint on your Markdown files using the project docker image
    language: docker_image
    files: \.(md|mdown|markdown)$
    entry: markdownlint/markdownlint
