repos:
- repo: local
  hooks:
  - id: markdownlint
    name: Markdownlint
    description: Run markdownlint on your Markdown files
    entry: mdl
    language: system
    files: \.(md|mdown|markdown)$
